# Generated by Django 4.1.1 on 2022-10-01 17:01

from django.db import migrations, models
import django.db.models.deletion
import movie.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=3000)),
                ('movie_cover', models.FileField(upload_to=movie.models.get_file_path)),
                ('genre', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movie.genre')),
            ],
        ),
    ]
