# Generated by Django 4.1.1 on 2022-10-07 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0007_alter_movie_dislikes_alter_movie_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dislikes',
            field=models.ManyToManyField(related_name='movies_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='likes',
            field=models.ManyToManyField(related_name='movies_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
