# Generated by Django 4.1.1 on 2022-10-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_movie_number_of_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='number_of_views',
        ),
        migrations.AddField(
            model_name='movie',
            name='number_of_views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
